config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources 'rooms'
  root 'rooms#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
class Message < ApplicationRecord
  after_create do
    ActionCable.server.broadcast "room_channel_#{self.room_id}", { message: content }
  end

  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages
  has_many :attendees
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :attendee
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:show]

  def index
    @rooms = Room.all
  end

  def show
    @messages = @room.messages.order('id DESC')
    @users = @room.attendees.map(&:user)
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(room_params)

    if @room.save!
      redirect_to @room
    else
      render 'new'
    end
  end

  def destroy
  end

  private

  def set_room
    @room = Room.find(params[:id])
  end

  def room_params
    params.require(:room).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Proof
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
%body{"data-room-id" => "#{@room.id if @room}"}
  - if current_user
    = link_to 'sign out', destroy_user_session_path, method: :delete
  %p.notice
    = notice
  %p.alert
    = alert
  = yield

app/views/rooms/index.html.haml
%h3
  Rooms

= link_to 'create new room', new_room_path

%p
  list:
%ul
- @rooms.each do |room|
  %li
    = link_to room.name, room_path(room)

app/views/rooms/new.html.haml
%h3= 'New room'

= form_for @room do |f|
  %p
    = f.label :name
    = f.text_field :name
  %p
    = f.submit

= link_to 'back', rooms_path

app/views/rooms/show.html.haml
%h3
  = "Room #{@room.name}"

%p
  = link_to 'back', rooms_path

%div#message-form
  %input#message{type: 'text'}
  %button.submitBtn
    Add
%ul#attendees
  - @users.each do |user|
    - userId = "user_#{user.id}"
    %li{id: userId }
      = user.email
%ul.messages
  - @messages.each do |message|
    %li
      = message.content

:javascript
  $(document).ready(function() {
    var roomId = $('body').data('room-id')
    App.Channels.Room.subscribe(roomId)
    $('#message-form .submitBtn').click(function(event) {
      var inputMessage = $('#message')
      var value = inputMessage.val()
      inputMessage.val('')
      App.room.speak({ value: value })
    })
  })